apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: management
  source:
    directory:
      jsonnet: {}
      recurse: false
    path: ocp/deployments
    repoURL: git@github.com:leonsteinhaeuser/rh-ocp-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions:
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
