apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-management
rules:
- apiGroups:
  - 'argoproj.io'
  resources:
  - 'appprojects'
  - 'applications'
  - 'applicationsets'
  verbs:
  - '*'
- apiGroups:
    - security.istio.io
  resources:
    - peerauthentications
    - authorizationpolicies
  verbs:
    - '*'
- apiGroups:
    - networking.istio.io
  resources:
    - destinationrules
    - gateways
    - virtualservices
    - serviceentries
  verbs:
    - '*'
- apiGroups:
    - cert-manager.io
  resources:
    - issuers
    - certificates
  verbs:
    - '*'
