apiVersion: v1
kind: ServiceAccount
metadata:
  name: &name status-service
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: microservices-demo
