apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: basic
  namespace: example-application-basic
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: example-application-basic
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - git@github.com:leonsteinhaeuser/rh-ocp-examples.git
status: {}
