apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: kubeadmin
    openshift.io/sa.scc.mcs: s0:c26,c20
    openshift.io/sa.scc.supplemental-groups: 65535/10000
    openshift.io/sa.scc.uid-range: 65535/10000
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    istio-injection: enabled
  name: example-application-basic-servicemesh
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: basic-servicemesh
  labels:
    argocd.argoproj.io/sync-wave: "0"
spec:
  sourceNamespaces:
    - example-application-basic-servicemesh
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: example-application-basic-servicemesh
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - git@github.com:leonsteinhaeuser/rh-ocp-examples.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: &ns example-application-basic-servicemesh
  labels:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: *ns
    server: https://kubernetes.default.svc
  project: basic-servicemesh
  source:
    path: ocp/deployments/manifests/servicemesh
    repoURL: git@github.com:leonsteinhaeuser/rh-ocp-examples.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions:
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
