apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: kubeadmin
    #openshift.io/sa.scc.mcs: s0:c26,c20
    #openshift.io/sa.scc.supplemental-groups: 65535/10000
    #openshift.io/sa.scc.uid-range: 65535/10000
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: hcp-operators
