apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: progressive
  namespace: example-application-progressive
  labels:
    argocd.argoproj.io/sync-wave: "0"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: example-application-progressive
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - git@github.com:leonsteinhaeuser/rh-ocp-examples.git
status: {}
