replicaCount: 3
image:
  repository: ghcr.io/leonsteinhaeuser/rh-ocp-examples-view
  pullPolicy: Always
  tag: main

serviceAccount:
  automount: false

podSecurityContext:
  fsGroup: 65535
  runAsUser: 65535
  runAsGroup: 65535

securityContext:
  runAsUser: 65535
  runAsGroup: 65535
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

resources:
  limits:
    cpu: 100m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 32Mi

route:
  enabled: true
  host: view-service-helm-basic.localhost
