apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name view-service
spec:
  isCA: true
  commonName: view-service-mesh.localhost
  secretName: *name
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cluster-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
